let p = "Vader Maul Palpatine Dooku Feynman Oppenheimer Einstein Fermi Drake Future Dot J Cole Metro Mustard 40 Dre Peyton Manning Tom Rodgers Mahomes LeBron Steph Ant KD Nadal Fed Djokovic Murray Deion PS2 Sauce Champ Joe Munoz Alex Mack Jason Kelce Kenobi Luke Skywalker Anakin Ahsoka Zoey Gem Barley Benny Turner Saban Dabo Laird Me Andrew Joey Alex Musk Zuck Bill Gates Steve Jobs Harvey Mike Donna Jessica Cartman Kenny Kyle Stan Sheldon Leonard Raj Penny Meemaw Sheldon's mom George Georgie Spiderman Iron Man Captain America Thor Batman Superman Joker Catwoman Homelander A Train Butcher Neumann LTT Austin Marques Jay Cypher Sage Astra Omen Charlie Brown Snooy Linus Lucy Midas Brutus Skye TnTina"
let people = [
    "Vader", 
    "Maul", 
    "Palpatine",
    "Dooku",
    "Feynman",
    "Oppenheimer",
    "Einstein",
    "Fermi",
    "Drake",
    "Future",
    "Dot",
    "J Cole",
    "Metro",
    "Mustard",
    "40",
    "Dre",
    "Peyton Manning",
    "Tom",
    "Rodgers",
    "Mahomes",
    "LeBron",
    "Steph",
    "Ant",
    "KD",
    "Nadal",
    "Fed",
    "Djokovic",
    "Murray",
    "Deion",
    "PS2",
    "Sauce",
    "Champ",
    "Joe",
    "Munoz",
    "Alex Mack",
    "Jason Kelce",
    "Kenobi",
    "Luke Skywalker",
    "Anakin",
    "Ahsoka",
    "Zoey",
    "Gem",
    "Barley",
    "Benny",
    "Turner",
    "Saban",
    "Dabo",
    "Laird",
    "Me",
    "Andrew",
    "Joey",
    "Alex",
    "Musk",
    "Zuck",
    "Bill Gates",
    "Steve Jobs",
    "Harvey",
    "Mike",
    "Donna",
    "Jessica",
    "Cartman",
    "Kenny",
    "Kyle",
    "Stan",
    "Sheldon",
    "Leonard",
    "Raj",
    "Penny",
    "Meemaw",
    "Sheldon's mom",
    "George",
    "Georgie",
    "Spiderman",
    "Iron Man",
    "Captain America",
    "Thor",
    "Batman",
    "Superman",
    "Joker",
    "Catwoman",
    "Homelander",
    "A Train",
    "Butcher",
    "Neumann",
    "LTT",
    "Austin",
    "Marques",
    "Jay",
    "Cypher",
    "Sage",
    "Astra",
    "Omen",
    "Charlie Brown",
    "Snoopy",
    "Linus",
    "Lucy",
    "Midas",
    "Brutus",
    "Skye",
    "TnTina"
]

let ac = "swinging falling spinning aiming unlocking detonating writing splitting batghing smoking walking up riding floating grilling picking up gluing throwing fumbling slinging opening dunking shooting stepping on slithering on making checking the time lifting covering themselves waving playing pouring putting on stretching benching pulling  watching slicing racing burning closing jumping sneezing drinking sliding on yelling walking out burning down drawing eating scanning sprinting through setting down tweeting on printing paying announcing slicking back remembering ryping staring serving mopping slapping stanning putting together reading answering putting the fries in the making praying drinking blocking shooting stopping guarding wielding drviing breaking off blowing up stealing lasering shooting up splitting in half popping dropping wearing reviewing putting taking picutre with buliding pointing teleporting toasting fighting sucking on bobbing touching scanning swimming shooting an arrow"
let actions = [
    "swinging",
    "falling",
    "spinning",
    "aiming",
    "unlocking",
    "detonating",
    "writing",
    "splitting",
    "bathing",
    "smoking",
    "walking up",
    "riding",
    "floating",
    "grilling",
    "picking up",
    "gluing",
    "throwing",
    "fumbling",
    "slinging",
    "opening",
    "dunking",
    "shooting",
    "stepping on",
    "slithering on",
    "making",
    "checking the time",
    "lifting",
    "covering themselves",
    "waving",
    "playing",
    "pouring",
    "putting on",
    "stretching",
    "benching",
    "pulling",
    "watching",
    "slicing",
    "racing",
    "burning",
    "closing",
    "jumping",
    "sneezing",
    "drinking",
    "sliding on",
    "yelling",
    "walking out",
    "burning down",
    "drawing",
    "eating",
    "scanning",
    "sprinting through",
    "setting down",
    "tweeting on",
    "printing",
    "paying",
    "announcing",
    "slicking back",
    "remembering",
    "typing",
    "staring",
    "serving",
    "mopping",
    "slapping",
    "stanning",
    "putting together",
    "reading",
    "answering",
    "putting the fries in the",
    "making",
    "praying",
    "drinking",
    "blocking",
    "shooting",
    "stopping",
    "guarding",
    "wielding",
    "driving",
    "breaking off",
    "blowing up",
    "stealing",
    "lasering",
    "shooting up",
    "splitting in half",
    "popping",
    "dropping",
    "wearing",
    "reviewing",
    "putting",
    "taking picture with",
    "buliding",
    "pointing",
    "teleporting",
    "toasting",
    "fighting",
    "sucking on",
    "bobbing",
    "touching",
    "scanning",
    "swimming",
    "shooting an arrow",
]

let ob = "lightsaber hole chair blaster safe bomb blackbaord atom cottage cheese weed stairs bike cloud burgers cane paper mache couch snow globe blanket can lamp basketball ant basketball court clay pot watch trophy mud glow stick ps2 ranch medal hamstring table Mack truck film meat pod racer lava door bed glitter beer table turf tunnel radio station plays cheez its mints paper hummus remote photo toll fare iPhone hair deck of cards keyboard window chilli floor beef Wow molecules marvel comics tech support bag brisket pew beer sled webs moon ice hammer Batmobile plane wing boat jewles pilot controls V table heads computer cat ear headphones Mac GPU camera ice home map high ground bread table thumb apples gold key card sharks Wii archery target"
let objects = [
    "lightsaber",
    "hole",
    "chair",
    "blaster",
    "safe",
    "bomb",
    "blackboard",
    "atom",
    "cottage cheese",
    "weed",
    "stairs",
    "bike",
    "cloud",
    "burgers",
    "cane",
    "paper mache",
    "couch",
    "snow globe",
    "blanket",
    "can",
    "lamp",
    "basketball",
    "ant",
    "basketball court",
    "clay pot",
    "on his watch",
    "trophy",
    "mud",
    "glow stick",
    "ps2",
    "ranch",
    "medal",
    "hamstring",
    "table",
    "Mack truck",
    "film",
    "meat",
    "pod racer",
    "in lava",
    "door",
    "bed",
    "glitter",
    "beer",
    "table",
    "turf",
    "tunnel",
    "radio station",
    "plays",
    "cheez its",
    "mints",
    "paper",
    "hummus",
    "remote",
    "recipe",
    "toll fare",
    "iPhone",
    "hair",
    "deck of cards",
    "on keyboard",
    "window",
    "chili",
    "floor",
    "beef",
    "WoW",
    "molecules",
    "marvel comics",
    "tech support",
    "bag",
    "brisket",
    "pew",
    "beer",
    "sled",
    "webs",
    "moon",
    "ice",
    "hammer",
    "Batmobile",
    "plane wing",
    "boat",
    "jewels",
    "pilot controls",
    "V",
    "mouse",
    "heads",
    "computer",
    "cat ear headphones",
    "Mac",
    "GPU",
    "camera",
    "ice home",
    "map",
    "high ground",
    "bread",
    "table",
    "thumb",
    "apples",
    "gold",
    "key card",
    "sharks",
    "Wii archery target",
];
let imagePaths = [
    "1ad.svg",
    "1bh.svg",
    "1cs.svg",
    "1dc.svg",
    "2ad.svg",
    "2bh.svg",
    "2cs.svg",
    "2dc.svg",
    "3ad.svg",
    "3bh.svg",
    "3cs.svg",
    "3dc.svg",
    "4ad.svg",
    "4bh.svg",
    "4cs.svg",
    "4dc.svg",
    "5ad.svg",
    "5bh.svg",
    "5cs.svg",
    "5dc.svg",
    "6ad.svg",
    "6bh.svg",
    "6cs.svg",
    "6dc.svg",
    "7ad.svg",
    "7bh.svg",
    "7cs.svg",
    "7dc.svg",
    "8ad.svg",
    "8bh.svg",
    "8cs.svg",
    "8dc.svg",
    "9ad.svg",
    "9bh.svg",
    "9cs.svg",
    "9dc.svg",
    "10ad.svg",
    "10bh.svg",
    "10cs.svg",
    "10dc.svg",
    "jad.svg",
    "jbh.svg",
    "jcs.svg",
    "jdc.svg",
    "qad.svg",
    "qbh.svg",
    "qcs.svg",
    "qdc.svg",
    "rad.svg",
    "rbh.svg",
    "rcs.svg",
    "rdc.svg"
]
/*
let prefixes = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'j', 'q', 'r'];
let images = []
need to loop over prefixes 
for every prefix, need to go through each one
 for (let i = 1; i<=13; i++){
    console.log(i)
    let prefix = prefixes[i - 1]
    let newarr = []
    for (let j = 1; j<=4; j++){
        if (j == 1){
            newarr[j - 1] = prefix + 'ad.svg' 
        }
        else if (j == 2){
            newarr[j - 1] = prefix + 'bh.svg' 
        }
        else if (j == 3){
            newarr[j - 1] = prefix + 'cs.svg' 
        }
        else if (j == 4){
            newarr[j - 1] = prefix + 'dc.svg' 
        }
    }
    images[i - 1] = newarr
}


console.log(images.reduce(function(a, b) {
    return a.concat(b)
}))
*/
export {people, actions, objects, imagePaths}